// 初年次教育科目（初ゼミ）のデータ
export interface FirstYearEducationCourse {
  courseCode: string;
  courseName: string;
  instructor: string;
  day: string;
  period: string;
  classroom: string;
  note: string;
  // レビューデータ
  evaluationCriteria: string[];
  testAllowance: string[];
  goodPoints: string[];
  badPoints: string[];
  otherInfo: string[];
}

export const firstYearEducationCourses: FirstYearEducationCourse[] = [
  // 月曜5限
  {
    courseCode: '1GBA001088',
    courseName: '疫学を学ぼう～健康問題を紐解く手法～-a',
    instructor: '福島　若葉',
    day: '月',
    period: '5限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001092',
    courseName: '疫学を学ぼう～健康問題を紐解く手法～-b',
    instructor: '福島　若葉',
    day: '月',
    period: '5限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  
  // 火曜1限
  {
    courseCode: '1GBA001005',
    courseName: '日本近現代史の諸問題について-a',
    instructor: '火+A12:A42',
    day: '火',
    period: '1限',
    classroom: '666小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001006',
    courseName: '日本近現代史の諸問題について-b',
    instructor: '住友　陽文',
    day: '火',
    period: '1限',
    classroom: '667小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001007',
    courseName: '判例を読むー法学や刑事事件が好きな人へ-a',
    instructor: '松倉　治代',
    day: '火',
    period: '1限',
    classroom: '505小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001008',
    courseName: '判例を読むー法学や刑事事件が好きな人へ-b',
    instructor: '松倉　治代',
    day: '火',
    period: '1限',
    classroom: '506小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001009',
    courseName: '海洋の環境と利用の科学-a',
    instructor: '片山　徹',
    day: '火',
    period: '1限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001010',
    courseName: '海洋の環境と利用の科学-b',
    instructor: '片山　徹',
    day: '火',
    period: '1限',
    classroom: '510小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001011',
    courseName: '光と物質のふしぎ-a',
    instructor: '松岡　雅也',
    day: '火',
    period: '1限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001012',
    courseName: '光と物質のふしぎ-b',
    instructor: '松井　康哲',
    day: '火',
    period: '1限',
    classroom: '513小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001013',
    courseName: '子どもの事故防止',
    instructor: '仁尾　かおり',
    day: '火',
    period: '1限',
    classroom: '511小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001020',
    courseName: '誰一人取り残さない社会について考えよう',
    instructor: '森本　明子',
    day: '火',
    period: '1限',
    classroom: '512小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001121',
    courseName: '食で支える健康と他分野との関わり-a',
    instructor: '桑原　晶子',
    day: '火',
    period: '1限',
    classroom: '306小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001122',
    courseName: '食で支える健康と他分野との関わり-b',
    instructor: '桑原　晶子',
    day: '火',
    period: '1限',
    classroom: '307小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001124',
    courseName: '創薬と社会－薬と社会のつながりを考える-a',
    instructor: '道上　雅孝',
    day: '火',
    period: '1限',
    classroom: '544小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001125',
    courseName: '創薬と社会－薬と社会のつながりを考える-b',
    instructor: '道上　雅孝',
    day: '火',
    period: '1限',
    classroom: '545小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 火曜2限
  {
    courseCode: '1GBA001003',
    courseName: '人工知能を知り，考える-a',
    instructor: '増山　直輝',
    day: '火',
    period: '2限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001014',
    courseName: '日本の学校は当たり前か？-a',
    instructor: '田村　徳子',
    day: '火',
    period: '2限',
    classroom: '505小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001015',
    courseName: '日本の学校は当たり前か？-b',
    instructor: '田村　徳子',
    day: '火',
    period: '2限',
    classroom: '506小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001016',
    courseName: '人権と差別について考える',
    instructor: '廣岡　浄進',
    day: '火',
    period: '2限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '期末レポート', '毎回の課題', 'プレゼンテーション', 'フィールドワーク'],
    testAllowance: [],
    goodPoints: ['AAが1人で他は全員Aだったから成績評価は割と緩い。'],
    badPoints: ['本読みや4000字の期末レポート、1人10分～15分の個人発表など課題が重たい。'],
    otherInfo: ['結構めんどくさい課題が多いけど、成し遂げたら達成感はある。']
  },
  {
    courseCode: '1GBA001017',
    courseName: '部落問題と日本社会',
    instructor: '廣岡　浄進',
    day: '火',
    period: '2限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001018',
    courseName: '哲学ってどんなこと？-a',
    instructor: '佐金　武',
    day: '火',
    period: '2限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001019',
    courseName: '哲学ってどんなこと？-b',
    instructor: '佐金　武',
    day: '火',
    period: '2限',
    classroom: '510小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001021',
    courseName: '人の行為や体験からデザインを考える-a',
    instructor: '土井　俊央',
    day: '火',
    period: '2限',
    classroom: '512小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001023',
    courseName: '人の行為や体験からデザインを考える-b',
    instructor: '土井　俊央',
    day: '火',
    period: '2限',
    classroom: '513小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001024',
    courseName: '光科学入門-a',
    instructor: '松田　拓也',
    day: '火',
    period: '2限',
    classroom: '544小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001025',
    courseName: '光科学入門-b',
    instructor: '松田　拓也',
    day: '火',
    period: '2限',
    classroom: '545小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001132',
    courseName: 'ガソリン車とEV：乗るならどっち？-a',
    instructor: '中谷　隼人',
    day: '火',
    period: '2限',
    classroom: '604小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001133',
    courseName: 'ガソリン車とEV：乗るならどっち？-b',
    instructor: '中谷　隼人',
    day: '火',
    period: '2限',
    classroom: '605小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001134',
    courseName: '健康をはかるしくみについて考えよう-a',
    instructor: '吉本　佳世',
    day: '火',
    period: '2限',
    classroom: '707小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '期末レポート', '中間レポート', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['先生優しいし、ゆるい。', '前半は少しめんどくさいですが、後半は楽勝です。期末レポートは感想書くだけです。発表も準備は全部授業中にできます。'],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001135',
    courseName: '健康をはかるしくみについて考えよう-b',
    instructor: '吉本　佳世',
    day: '火',
    period: '2限',
    classroom: '708小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '期末レポート', '中間レポート', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['先生優しいし、ゆるい。', '前半は少しめんどくさいですが、後半は楽勝です。期末レポートは感想書くだけです。発表も準備は全部授業中にできます。'],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001136',
    courseName: '沈黙の臓器・肝臓から健康を考える-a',
    instructor: '打田　佐和子',
    day: '火',
    period: '2限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001137',
    courseName: '沈黙の臓器・肝臓から健康を考える-b',
    instructor: '打田　佐和子',
    day: '火',
    period: '2限',
    classroom: '609小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001138',
    courseName: 'ヒトの運動制御について-a',
    instructor: '平岡　浩一',
    day: '火',
    period: '2限',
    classroom: '666小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001139',
    courseName: 'ヒトの運動制御について-b',
    instructor: '平岡　浩一',
    day: '火',
    period: '2限',
    classroom: '667小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001141',
    courseName: 'リハビリから考える「共に働く社会とは」-a',
    instructor: '内藤　泰男',
    day: '火',
    period: '2限',
    classroom: '701小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001142',
    courseName: 'リハビリから考える「共に働く社会とは」-b',
    instructor: '内藤　泰男',
    day: '火',
    period: '2限',
    classroom: '702小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001143',
    courseName: '親子保健について考える',
    instructor: '緒方　靖恵',
    day: '火',
    period: '2限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '期末レポート', 'プレゼンテーション'],
    testAllowance: ['テストなし'],
    goodPoints: ['本当に楽しい', '検査を実際にできる', 'グループ分けから行動科学を利用するため、自分と似ている人とグループワークができる', '他学部の子と他のゼミよりも仲良くなれると思う', '先生もフレンドリーですごく楽しかった'],
    badPoints: ['隠匿情報検査や行動科学についてグループで調べまくったり実際に検査したものを分析しないといけないから、興味がない人にはしんどいかも', 'プレゼンテーションがおおい', '自分の話を全員にする時間がある'],
    otherInfo: []
  },
  {
    courseCode: '1GBA001144',
    courseName: 'ネット社会におけるヘルスリテラシー',
    instructor: '森木　ゆう子',
    day: '火',
    period: '2限',
    classroom: '511小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001145',
    courseName: 'フレイルを予防する地域づくり',
    instructor: '根来　佐由美',
    day: '火',
    period: '2限',
    classroom: '517小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001146',
    courseName: '子育てと環境について考えてみよう',
    instructor: '戸田　まどか',
    day: '火',
    period: '2限',
    classroom: '610小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001174',
    courseName: '人工知能を知り，考える-b',
    instructor: '増山　直輝',
    day: '火',
    period: '2限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 火曜3限
  {
    courseCode: '1GBA001027',
    courseName: '近代新漢語の成立と展開を探究する-a',
    instructor: '大島　英之',
    day: '火',
    period: '3限',
    classroom: '308小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001028',
    courseName: '近代新漢語の成立と展開を探究する-b',
    instructor: '大島　英之',
    day: '火',
    period: '3限',
    classroom: '309小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001029',
    courseName: 'ロシアと中央ユーラシアの歴史と文化-a',
    instructor: '濱本　真実',
    day: '火',
    period: '3限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001030',
    courseName: 'ロシアと中央ユーラシアの歴史と文化-b',
    instructor: '濱本　真実',
    day: '火',
    period: '3限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001031',
    courseName: 'ITサービス-a',
    instructor: '田中　俊二',
    day: '火',
    period: '3限',
    classroom: '505小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001032',
    courseName: 'ITサービス-b',
    instructor: '田中　俊二',
    day: '火',
    period: '3限',
    classroom: '506小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001033',
    courseName: '地名が伝える情報-a',
    instructor: '永田　好克',
    day: '火',
    period: '3限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001034',
    courseName: '地名が伝える情報-b',
    instructor: '永田　好克',
    day: '火',
    period: '3限',
    classroom: '508小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001035',
    courseName: 'ローカルとグローバルで考える環境課題-a',
    instructor: '竹内　やよい',
    day: '火',
    period: '3限',
    classroom: '607小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001036',
    courseName: 'ローカルとグローバルで考える環境課題-b',
    instructor: '竹内　やよい',
    day: '火',
    period: '3限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001140',
    courseName: 'AIプロダクトデザイン-a',
    instructor: '石丸　翔也',
    day: '火',
    period: '3限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001147',
    courseName: '脳を構成する細胞について考える',
    instructor: '高野　桂',
    day: '火',
    period: '3限',
    classroom: '545小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001148',
    courseName: '人と動物との関わりを考える',
    instructor: '土赤　忍',
    day: '火',
    period: '3限',
    classroom: '502小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001149',
    courseName: 'うつ病を知り、予防しよう-a',
    instructor: '井上　貴雄',
    day: '火',
    period: '3限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '期末レポート', '中間レポート', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['先生が優しい。レポートもあるけどそこまで重くない。評価基準を出してくれるのはありがたい。レポートやプレゼンの準備用の休講が多い。ほとんどの授業で15分くらい早く終わる。', '教授が温厚。うつ病についての授業が面白い。レポートの書き方やプレゼンの作り方を学べる。医学系の論文サイトの使い方を学べる。'],
    badPoints: ['レポートやプレゼンの準備が少し大変。期日に余裕を持ってやった方が良い。'],
    otherInfo: ['先生曰く誰も落としたことがないそうです。']
  },
  {
    courseCode: '1GBA001150',
    courseName: 'うつ病を知り、予防しよう-b',
    instructor: '井上　貴雄',
    day: '火',
    period: '3限',
    classroom: '510小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '期末レポート', '中間レポート', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['先生が優しい。レポートもあるけどそこまで重くない。評価基準を出してくれるのはありがたい。レポートやプレゼンの準備用の休講が多い。ほとんどの授業で15分くらい早く終わる。', '教授が温厚。うつ病についての授業が面白い。レポートの書き方やプレゼンの作り方を学べる。医学系の論文サイトの使い方を学べる。'],
    badPoints: ['レポートやプレゼンの準備が少し大変。期日に余裕を持ってやった方が良い。'],
    otherInfo: ['先生曰く誰も落としたことがないそうです。']
  },
  {
    courseCode: '1GBA001152',
    courseName: '苦情対応について考える-a',
    instructor: '岩井　千春',
    day: '火',
    period: '3限',
    classroom: '511小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001153',
    courseName: '苦情対応について考える-b',
    instructor: '岩井　千春',
    day: '火',
    period: '3限',
    classroom: '512小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001154',
    courseName: '英語の謎をさぐる-a',
    instructor: '山本　修',
    day: '火',
    period: '3限',
    classroom: '513小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001155',
    courseName: '英語の謎をさぐる-b',
    instructor: '山本　修',
    day: '火',
    period: '3限',
    classroom: '514小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001156',
    courseName: 'スポーツでつながる地域共創-a',
    instructor: '松竹　貴大',
    day: '火',
    period: '3限',
    classroom: '543小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001157',
    courseName: 'スポーツでつながる地域共創-b',
    instructor: '松竹　貴大',
    day: '火',
    period: '3限',
    classroom: '544小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001160',
    courseName: 'AIプロダクトデザイン-b',
    instructor: '石丸　翔也',
    day: '火',
    period: '3限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001197',
    courseName: '初めての多文化コミュニケーション-a',
    instructor: 'ＭＯＨＡＭＭＡＤ　ＭＯＩＮＵＤＤＩＮ',
    day: '火',
    period: '3限',
    classroom: '701小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001198',
    courseName: '初めての多文化コミュニケーション-b',
    instructor: 'ＭＯＨＡＭＭＡＤ　ＭＯＩＮＵＤＤＩＮ',
    day: '火',
    period: '3限',
    classroom: '702小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 火曜4限
  {
    courseCode: '1GBA001038',
    courseName: '社会科学の古典を読む-a',
    instructor: '山本　泰三',
    day: '火',
    period: '4限',
    classroom: '506小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001039',
    courseName: '社会科学の古典を読む-b',
    instructor: '山本　泰三',
    day: '火',
    period: '4限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001040',
    courseName: '因数分解　再入門-a',
    instructor: '吉田　雅通',
    day: '火',
    period: '4限',
    classroom: '508小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001041',
    courseName: '因数分解　再入門-b',
    instructor: '吉田　雅通',
    day: '火',
    period: '4限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001042',
    courseName: '地震災害を考えよう-a',
    instructor: '角掛　久雄',
    day: '火',
    period: '4限',
    classroom: '543小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001043',
    courseName: '地震災害を考えよう-b',
    instructor: '角掛　久雄',
    day: '火',
    period: '4限',
    classroom: '544小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001044',
    courseName: 'ADASから自動運転へ：現状と課題の調査-a',
    instructor: '江　易翰',
    day: '火',
    period: '4限',
    classroom: '604小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001045',
    courseName: 'ADASから自動運転へ：現状と課題の調査-b',
    instructor: '江　易翰',
    day: '火',
    period: '4限',
    classroom: '605小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001046',
    courseName: '伝わる書き方・伝わる文章を考える-a',
    instructor: '野田　三貴',
    day: '火',
    period: '4限',
    classroom: '310小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001047',
    courseName: '伝わる書き方・伝わる文章を考える-b',
    instructor: '野田　三貴',
    day: '火',
    period: '4限',
    classroom: '312小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001048',
    courseName: '身の回りの市販薬はどのように効くのか？-a',
    instructor: '坂本　健太郎',
    day: '火',
    period: '4限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001049',
    courseName: '身の回りの市販薬はどのように効くのか？-b',
    instructor: '坂本　健太郎',
    day: '火',
    period: '4限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001050',
    courseName: '外国人との共生社会と異文化理解-a',
    instructor: '藤岡　真由美',
    day: '火',
    period: '4限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001051',
    courseName: '外国人との共生社会と異文化理解-b',
    instructor: '藤岡　真由美',
    day: '火',
    period: '4限',
    classroom: '609小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001052',
    courseName: 'フランスの社会と文化-a',
    instructor: '小澤　真',
    day: '火',
    period: '4限',
    classroom: '610小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001119',
    courseName: '健康まちづくり・アクションゼミ-a',
    instructor: '川端　悠',
    day: '火',
    period: '4限',
    classroom: '708小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001151',
    courseName: 'フランスの社会と文化-b',
    instructor: '小澤　真',
    day: '火',
    period: '4限',
    classroom: '611小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001161',
    courseName: '健康まちづくり・アクションゼミ-b',
    instructor: '川端　悠',
    day: '火',
    period: '4限',
    classroom: '709小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001163',
    courseName: '今のリアルから未来を読み解き社会に問う-a',
    instructor: '市田　秀樹',
    day: '火',
    period: '4限',
    classroom: '665小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001164',
    courseName: '今のリアルから未来を読み解き社会に問う-b',
    instructor: '市田　秀樹',
    day: '火',
    period: '4限',
    classroom: '666小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001165',
    courseName: '謎解きの古書体学に挑戦してみよう‼-a',
    instructor: '佐々木　博光',
    day: '火',
    period: '4限',
    classroom: '701小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001166',
    courseName: '謎解きの古書体学に挑戦してみよう‼-b',
    instructor: '佐々木　博光',
    day: '火',
    period: '4限',
    classroom: '702小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001167',
    courseName: '大学で学び考える基本を身につけよう！-a',
    instructor: '飯吉　弘子',
    day: '火',
    period: '4限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '中間レポート', '毎回の課題', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['殆どの人が凝ったものを作ってくるので、聞いてて面白い。', 'レポートのテーマについて色々調べるので、一分野に詳しくなれる。', '先生が優しい。学情に詳しくなれる。'],
    badPoints: ['楽しいけど、テーマ選び失敗するとめっちゃ大変。いい感じのテーマ選んでた人は楽そうやった。'],
    otherInfo: ['テーマ選びさえ上手いことやれば、かなり楽だと思う。あと個人作業が多いので、他の学科の友達を作るのにはあまり向いてないかも。でも話しかけて仲良くなってた人はいた。']
  },
  {
    courseCode: '1GBA001168',
    courseName: '大学で学び考える基本を身につけよう！-b',
    instructor: '飯吉　弘子',
    day: '火',
    period: '4限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '中間レポート', '毎回の課題', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['殆どの人が凝ったものを作ってくるので、聞いてて面白い。', 'レポートのテーマについて色々調べるので、一分野に詳しくなれる。', '先生が優しい。学情に詳しくなれる。'],
    badPoints: ['楽しいけど、テーマ選び失敗するとめっちゃ大変。いい感じのテーマ選んでた人は楽そうやった。'],
    otherInfo: ['テーマ選びさえ上手いことやれば、かなり楽だと思う。あと個人作業が多いので、他の学科の友達を作るのにはあまり向いてないかも。でも話しかけて仲良くなってた人はいた。']
  },
  {
    courseCode: '1GBA001170',
    courseName: '興味関心を「縦と横と」に編み上げる-a',
    instructor: '平　知宏',
    day: '火',
    period: '4限',
    classroom: '510小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001171',
    courseName: '興味関心を「縦と横と」に編み上げる-b',
    instructor: '平　知宏',
    day: '火',
    period: '4限',
    classroom: '512小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001900',
    courseName: '〔再履修〕/全_森',
    instructor: '橋本　智也',
    day: '火',
    period: '4限',
    classroom: '769小教室',
    note: '',
    evaluationCriteria: ['毎回の課題', '小テスト', '出席点あり'],
    testAllowance: ['小テストはMoodle上で行われ、授業資料などを他のタブで自由に見れる。'],
    goodPoints: ['レポートやプレゼンの負担が少ない。遠隔で資料を読んどけばいい回が何度かある。出すだけで良い課題が多い。', '全く難しい課題はなく、本当に楽単。毎回の課題も「内容ではなく提出の有無で評価」とおっしゃっていたので、気楽に取り組めた。'],
    badPoints: ['静かすぎて友達ができない', 'ムードルで実施の回の課題がちょっとめんどい時がある'],
    otherInfo: ['たまに対面ではなく、資料配布のみの回がありました。']
  },

  // 火曜5限
  {
    courseCode: '1GBA001001',
    courseName: 'コンピュータで探る分子の世界-a',
    instructor: '麻田　俊雄',
    day: '火',
    period: '5限',
    classroom: '310小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001002',
    courseName: 'コンピュータで探る分子の世界-b',
    instructor: '麻田　俊雄',
    day: '火',
    period: '5限',
    classroom: '311小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001004',
    courseName: 'GISを使って地域のことを考えよう-a',
    instructor: '根本　達也',
    day: '火',
    period: '5限',
    classroom: '607小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '中間レポート', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['レポートが数回あったが、ほとんど授業内で提出できる。また、最終レポートは字数が200字ととても楽。プレゼンもゆるい。', 'その日の課題を授業中にやらせてくれるし、授業中に終わるので、ほぼ課題がない。', 'プレゼンはグループの1回のみなので、とても楽'],
    badPoints: ['インド人の先生の日本語が少し聞き取りづらい'],
    otherInfo: []
  },
  {
    courseCode: '1GBA001037',
    courseName: 'GISを使って地域のことを考えよう-b',
    instructor: '根本　達也',
    day: '火',
    period: '5限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '中間レポート', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['レポートが数回あったが、ほとんど授業内で提出できる。また、最終レポートは字数が200字ととても楽。プレゼンもゆるい。', 'その日の課題を授業中にやらせてくれるし、授業中に終わるので、ほぼ課題がない。', 'プレゼンはグループの1回のみなので、とても楽'],
    badPoints: ['インド人の先生の日本語が少し聞き取りづらい'],
    otherInfo: []
  },
  {
    courseCode: '1GBA001053',
    courseName: '不思議な粉の世界について知ろう',
    instructor: '野村　俊之',
    day: '火',
    period: '5限',
    classroom: '309小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001055',
    courseName: 'どのようにつくる？これからのエネルギー',
    instructor: '岡本　尚樹',
    day: '火',
    period: '5限',
    classroom: '308小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001056',
    courseName: '身のまわりの物質科学-a',
    instructor: '笠井　秀隆',
    day: '火',
    period: '5限',
    classroom: '307小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001057',
    courseName: '身のまわりの物質科学-b',
    instructor: '森　茂生',
    day: '火',
    period: '5限',
    classroom: '306小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001059',
    courseName: '生薬の効能は科学的に裏付けられているか',
    instructor: '小川　拓水',
    day: '火',
    period: '5限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001060',
    courseName: '生物と環境を元素の観点から考える',
    instructor: '反田　直之',
    day: '火',
    period: '5限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001175',
    courseName: '血液の病から考える医療と社会-a',
    instructor: '中前　博久',
    day: '火',
    period: '5限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001176',
    courseName: '血液の病から考える医療と社会-b',
    instructor: '中前　博久',
    day: '火',
    period: '5限',
    classroom: '508小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001177',
    courseName: '認知症の人にもやさしいまちを考える-a',
    instructor: '小松　亜弥音',
    day: '火',
    period: '5限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001178',
    courseName: '認知症の人にもやさしいまちを考える-b',
    instructor: '小松　亜弥音',
    day: '火',
    period: '5限',
    classroom: '510小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 水曜5限
  {
    courseCode: '1GBA001901',
    courseName: '〔再履修〕/全_森',
    instructor: '西垣　順子',
    day: '水',
    period: '5限',
    classroom: '769小教室',
    note: '',
    evaluationCriteria: ['出席点あり', '期末レポート', '中間レポート', '毎回の課題', 'プレゼンテーション'],
    testAllowance: ['テストはありませんでした。'],
    goodPoints: ['先生が優しく、内容も面白いところ。プレゼンの方法やレポートの書き方など丁寧に教えてくれたところ。', '授業中に他の事をしていてもほとんど無視してくれるのでオンデマンド授業の視聴を進められた。'],
    badPoints: ['特にないです。', '1番ひどいのは「グループワークがない」所です。生徒同士の会話は一切生まれない上にプレゼン発表(計2回)は個人で考えて個人で行いました。また、教育学の本をわざわざ購入する必要があり、それを読んだ上で行う毎回の課題がとてもめんどくさかったです。'],
    otherInfo: ['教授が雑談をすぐに始めるのですが、どの話も面白くないです。']
  },

  // 木曜2限
  {
    courseCode: '1GBA001058',
    courseName: '物理科学の世界をのぞいてみよう-a',
    instructor: '小菅　厚子',
    day: '木',
    period: '2限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001061',
    courseName: '物理科学の世界をのぞいてみよう-ｂ',
    instructor: '小菅　厚子',
    day: '木',
    period: '2限',
    classroom: '609小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001123',
    courseName: 'マーケティングで流行と衰退を考える-a',
    instructor: '薮野　祥太',
    day: '木',
    period: '2限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001126',
    courseName: 'マーケティングで流行と衰退を考える-b',
    instructor: '薮野　祥太',
    day: '木',
    period: '2限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 木曜3限
  {
    courseCode: '1GBA001162',
    courseName: '化石を調べよう-a',
    instructor: '桑原　希世子',
    day: '木',
    period: '3限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001169',
    courseName: '化石を調べよう-b',
    instructor: '桑原　希世子',
    day: '木',
    period: '3限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 木曜4限
  {
    courseCode: '1GBA001022',
    courseName: '都市から学ぶ社会問題-a',
    instructor: '川野　英二',
    day: '木',
    period: '4限',
    classroom: '513小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001073',
    courseName: '都市から学ぶ社会問題-b',
    instructor: '川野　英二',
    day: '木',
    period: '4限',
    classroom: '514小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001074',
    courseName: '社会科学で世の中を捉える-a',
    instructor: '中本　龍市',
    day: '木',
    period: '4限',
    classroom: '605小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001075',
    courseName: '社会科学で世の中を捉える-b',
    instructor: '中本　龍市',
    day: '木',
    period: '4限',
    classroom: '606小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001076',
    courseName: '学校教育の〈縁側〉をから考える-a',
    instructor: '鈴木　伸尚',
    day: '木',
    period: '4限',
    classroom: '665小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001077',
    courseName: '学校教育の〈縁側〉をから考える-b',
    instructor: '鈴木　伸尚',
    day: '木',
    period: '4限',
    classroom: '666小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001078',
    courseName: '数学と社会との繋がりについて考えよう-a',
    instructor: '川添　充',
    day: '木',
    period: '4限',
    classroom: '701小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001079',
    courseName: '数学と社会との繋がりについて考えよう-b',
    instructor: '川添　充',
    day: '木',
    period: '4限',
    classroom: '702小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001080',
    courseName: '思考実験：科学から身近な社会課題まで-a',
    instructor: '譚　ゴオン',
    day: '木',
    period: '4限',
    classroom: '707小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001081',
    courseName: '思考実験：科学から身近な社会課題まで-b',
    instructor: '譚　ゴオン',
    day: '木',
    period: '4限',
    classroom: '708小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001082',
    courseName: '遊びと人間ー遊びについて考えよう-a',
    instructor: '亀喜　信',
    day: '木',
    period: '4限',
    classroom: '709小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001179',
    courseName: '遊びと人間ー遊びについて考えよう-b',
    instructor: '亀喜　信',
    day: '木',
    period: '4限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001180',
    courseName: 'DNAで生き物の名前を調べてみよう-a',
    instructor: '奥崎　穣',
    day: '木',
    period: '4限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001181',
    courseName: 'DNAで生き物の名前を調べてみよう-b',
    instructor: '奥崎　穣',
    day: '木',
    period: '4限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001182',
    courseName: '正解のない時代をどう考えるか-AIと創作-a',
    instructor: '林　宣伶',
    day: '木',
    period: '4限',
    classroom: '305小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001183',
    courseName: '正解のない時代をどう考えるか-AIと創作-b',
    instructor: '林　宣伶',
    day: '木',
    period: '4限',
    classroom: '306小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001184',
    courseName: '〈地域活性化〉の未来を考える-a',
    instructor: '水野　遼太郎',
    day: '木',
    period: '4限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001185',
    courseName: '〈地域活性化〉の未来を考える-b',
    instructor: '水野　遼太郎',
    day: '木',
    period: '4限',
    classroom: '420小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 木曜5限
  {
    courseCode: '1GBA001054',
    courseName: '森之宮キャンパスあたりの地誌学-a',
    instructor: '菅野　拓',
    day: '木',
    period: '5限',
    classroom: '307小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001083',
    courseName: '森之宮キャンパスあたりの地誌学-b',
    instructor: '菅野　拓',
    day: '木',
    period: '5限',
    classroom: '308小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001084',
    courseName: '近世・近代の法制度から現代を考える-a',
    instructor: '安竹　貴彦',
    day: '木',
    period: '5限',
    classroom: '310小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001085',
    courseName: '近世・近代の法制度から現代を考える-b',
    instructor: '安竹　貴彦',
    day: '木',
    period: '5限',
    classroom: '311小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001086',
    courseName: '民事判例を読む-a',
    instructor: '古谷　貴之',
    day: '木',
    period: '5限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001087',
    courseName: '民事判例を読む-b',
    instructor: '古谷　貴之',
    day: '木',
    period: '5限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001089',
    courseName: '科学的思考事始',
    instructor: '中村　雅夫',
    day: '木',
    period: '5限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: ['出席点あり', '期末レポート', '中間レポート', 'プレゼンテーション'],
    testAllowance: [],
    goodPoints: ['研究で必要な考え方やスライドの見せ方など、基本的なことをわかりやすく教えてくれる。'],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001090',
    courseName: 'Aircraft in Disaster Response',
    instructor: 'アンドレエバ森　　アドリアナ',
    day: '木',
    period: '5限',
    classroom: '420小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001091',
    courseName: '身の回りにある動物の病気',
    instructor: '井澤　武史',
    day: '木',
    period: '5限',
    classroom: '701小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001113',
    courseName: '老化とは何か',
    instructor: '岩崎　忠',
    day: '木',
    period: '5限',
    classroom: '702小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001114',
    courseName: '今日の心臓手術-a',
    instructor: '高橋　洋介',
    day: '木',
    period: '5限',
    classroom: '604小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001115',
    courseName: '今日の心臓手術-b',
    instructor: '高橋　洋介',
    day: '木',
    period: '5限',
    classroom: '605小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001116',
    courseName: '高齢者の社会的孤立を考える',
    instructor: '（地）河野　あゆみ',
    day: '木',
    period: '5限',
    classroom: '606小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001117',
    courseName: 'エビデンスで考える超高齢社会へのヒント',
    instructor: '長畑　多代',
    day: '木',
    period: '5限',
    classroom: '607小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001118',
    courseName: '元素の科学-a',
    instructor: '谷口　暢一',
    day: '木',
    period: '5限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001187',
    courseName: '女性の健康にかかわる問題について考えよう',
    instructor: '玉上　麻美',
    day: '木',
    period: '5限',
    classroom: '505小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001188',
    courseName: '縁起でもない話をしよう',
    instructor: '三輪　恭子',
    day: '木',
    period: '5限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001189',
    courseName: '元素の科学-b',
    instructor: '谷口　暢一',
    day: '木',
    period: '5限',
    classroom: '609小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001199',
    courseName: '現代日本における文化的多様性の探究-a',
    instructor: '中野　遼子',
    day: '木',
    period: '5限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001200',
    courseName: '現代日本における文化的多様性の探究-b',
    instructor: '中野　遼子',
    day: '木',
    period: '5限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 金曜2限
  {
    courseCode: '1GBA001064',
    courseName: '対称性を科学する',
    instructor: '宍戸　寛明',
    day: '金',
    period: '2限',
    classroom: '502小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001072',
    courseName: '科学技術と安全性について考える',
    instructor: '和田　健司',
    day: '金',
    period: '2限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001111',
    courseName: '航空宇宙技術の社会的要請と未来技術-a',
    instructor: '新井　隆景',
    day: '金',
    period: '2限',
    classroom: '310小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001112',
    courseName: '航空宇宙技術の社会的要請と未来技術-b',
    instructor: '新井　隆景',
    day: '金',
    period: '2限',
    classroom: '311小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001172',
    courseName: '建築の世界-a',
    instructor: '石山　央樹',
    day: '金',
    period: '2限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001173',
    courseName: '建築の世界-b',
    instructor: '石山　央樹',
    day: '金',
    period: '2限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 金曜3限
  {
    courseCode: '1GBA001101',
    courseName: '食と健康と社会-a',
    instructor: '松村　成暢',
    day: '金',
    period: '3限',
    classroom: '709小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001196',
    courseName: '食と健康と社会-b',
    instructor: '松村　成暢',
    day: '金',
    period: '3限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 金曜4限
  {
    courseCode: '1GBA001062',
    courseName: '「なにわ」の謎を解き明かす-a',
    instructor: '大塚　耕司',
    day: '金',
    period: '4限',
    classroom: '306小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001063',
    courseName: '「なにわ」の謎を解き明かす-b',
    instructor: '大塚　耕司',
    day: '金',
    period: '4限',
    classroom: '307小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001065',
    courseName: 'キャンパス周辺に潜む災害リスク-a',
    instructor: '伊藤　康人',
    day: '金',
    period: '4限',
    classroom: '604小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001066',
    courseName: 'キャンパス周辺に潜む災害リスク-b',
    instructor: '伊藤　康人',
    day: '金',
    period: '4限',
    classroom: '605小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001067',
    courseName: '家族介護とヤングケアラー-a',
    instructor: '濱島　淑恵',
    day: '金',
    period: '4限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001068',
    courseName: '家族介護とヤングケアラー-b',
    instructor: '濱島　淑恵',
    day: '金',
    period: '4限',
    classroom: '609小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001069',
    courseName: '社会の諸問題について調べ、知識を広げる-a',
    instructor: '谷　政敏',
    day: '金',
    period: '4限',
    classroom: '610小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001070',
    courseName: '社会の諸問題について調べ、知識を広げる-b',
    instructor: '谷　政敏',
    day: '金',
    period: '4限',
    classroom: '611小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001071',
    courseName: '母語としての日本語・Ｌ２としての日本語-a',
    instructor: '森田　耕平',
    day: '金',
    period: '4限',
    classroom: '701小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001093',
    courseName: '感想文からレポートへ-a',
    instructor: '森　瑞季',
    day: '金',
    period: '4限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001094',
    courseName: '感想文からレポートへ-b',
    instructor: '森　瑞季',
    day: '金',
    period: '4限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001095',
    courseName: '地方自治とインフラ事業の未来を考える',
    instructor: '高野　恵亮',
    day: '金',
    period: '4限',
    classroom: '666小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001096',
    courseName: '官民連携とまちづくりについて考える',
    instructor: '佐野　修久',
    day: '金',
    period: '4限',
    classroom: '667小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001097',
    courseName: '街づくりにおける地域熱供給の役割-a',
    instructor: '鍋島　美奈子',
    day: '金',
    period: '4限',
    classroom: '505小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001098',
    courseName: '街づくりにおける地域熱供給の役割-b',
    instructor: '鍋島　美奈子',
    day: '金',
    period: '4限',
    classroom: '506小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001099',
    courseName: 'SFにおける科学-a',
    instructor: '岡本　晃一',
    day: '金',
    period: '4限',
    classroom: '507小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001100',
    courseName: 'SFにおける科学-b',
    instructor: '岡本　晃一',
    day: '金',
    period: '4限',
    classroom: '508小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001120',
    courseName: '母語としての日本語・Ｌ２としての日本語-b',
    instructor: '森田　耕平',
    day: '金',
    period: '4限',
    classroom: '702小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001127',
    courseName: 'ＮＰＯの経営・寄付戦略を立てよう-a',
    instructor: '松岡　悠和',
    day: '金',
    period: '4限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001128',
    courseName: 'ＮＰＯの経営・寄付戦略を立てよう-b',
    instructor: '松岡　悠和',
    day: '金',
    period: '4限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001190',
    courseName: '古墳と環境について考える',
    instructor: '中村　彰宏',
    day: '金',
    period: '4限',
    classroom: '510小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001191',
    courseName: 'まちを観て読み解くLandscape Design',
    instructor: '松尾　薫',
    day: '金',
    period: '4限',
    classroom: '511小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001192',
    courseName: 'メタ認知を促す学習環境をつくってみよう-a',
    instructor: '土肥　美子',
    day: '金',
    period: '4限',
    classroom: '512小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001193',
    courseName: 'メタ認知を促す学習環境をつくってみよう-b',
    instructor: '水引　智央',
    day: '金',
    period: '4限',
    classroom: '509小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001194',
    courseName: '「働く」を科学的に考える-a',
    instructor: '中村　志津香',
    day: '金',
    period: '4限',
    classroom: '513小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001195',
    courseName: '「働く」を科学的に考える-b',
    instructor: '中村　志津香',
    day: '金',
    period: '4限',
    classroom: '514小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 金曜5限
  {
    courseCode: '1GBA001026',
    courseName: '見えない分子が生物を動かす-a',
    instructor: '秋山　康紀',
    day: '金',
    period: '5限',
    classroom: '512小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001102',
    courseName: '情報通信ネットワークのしくみとその役割-a',
    instructor: '関　勇弥',
    day: '金',
    period: '5限',
    classroom: '418小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001103',
    courseName: '情報通信ネットワークのしくみとその役割-b',
    instructor: '関　勇弥',
    day: '金',
    period: '5限',
    classroom: '419小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001104',
    courseName: 'はじめての数理モデリング-a',
    instructor: '山岡　直人',
    day: '金',
    period: '5限',
    classroom: '604小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001105',
    courseName: 'はじめての数理モデリング-b',
    instructor: '山岡　直人',
    day: '金',
    period: '5限',
    classroom: '605小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001106',
    courseName: '左手と右手の分子：キラリティーの不思議-a',
    instructor: '小島　秀夫',
    day: '金',
    period: '5限',
    classroom: '505小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001107',
    courseName: '左手と右手の分子：キラリティーの不思議-b',
    instructor: '小島　秀夫',
    day: '金',
    period: '5限',
    classroom: '506小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001108',
    courseName: '衝突安全性と自動車技術の未来を考える-a',
    instructor: '楳田　努',
    day: '金',
    period: '5限',
    classroom: '607小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001109',
    courseName: '衝突安全性と自動車技術の未来を考える-b',
    instructor: '楳田　努',
    day: '金',
    period: '5限',
    classroom: '608小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001110',
    courseName: 'バイオテクノロジーについて考えよう-a',
    instructor: '横山　智哉子',
    day: '金',
    period: '5限',
    classroom: '711小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001129',
    courseName: '植物の品種改良について考えよう',
    instructor: '手塚　孝弘',
    day: '金',
    period: '5限',
    classroom: '701小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001130',
    courseName: '進化を味わう：生物多様性と育種の科学',
    instructor: '白柿　薫平',
    day: '金',
    period: '5限',
    classroom: '702小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001131',
    courseName: '見えない分子が生物を動かす-b',
    instructor: '桝谷　貴洋',
    day: '金',
    period: '5限',
    classroom: '513小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001158',
    courseName: '健康医療を支えるくすりと医療機器の科学-a',
    instructor: '田中　大祐',
    day: '金',
    period: '5限',
    classroom: '709小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001159',
    courseName: '健康医療を支えるくすりと医療機器の科学-b',
    instructor: '田中　大祐',
    day: '金',
    period: '5限',
    classroom: '708小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },
  {
    courseCode: '1GBA001186',
    courseName: 'バイオテクノロジーについて考えよう-b',
    instructor: '横山　智哉子',
    day: '金',
    period: '5限',
    classroom: '710小教室',
    note: '抽選',
    evaluationCriteria: [],
    testAllowance: [],
    goodPoints: [],
    badPoints: [],
    otherInfo: []
  },

  // 時間割外
  {
    courseCode: '1GBA001902',
    courseName: '〔再履修〕/全_遠隔',
    instructor: '深野　政之',
    day: '時間割外',
    period: '',
    classroom: '遠隔授業',
    note: '',
    evaluationCriteria: ['出席点あり', '期末レポート', '中間レポート', '毎回の課題', 'プレゼンテーション', 'ディベート'],
    testAllowance: [],
    goodPoints: ['グループワークで他学部の人と仲良くなれる', '課題を出し忘れていたら教えてくれる。グループワークのメンバーによっては楽しめる。レポートの評価があまり良くなくても単位はくれる', 'ほとんどの人がAAを取れていたところ。結構グループワークをするので、他の受講生と仲良くなりやすいところ。', '出席点があり、教授は優しいところ'],
    badPoints: ['出席点あり、課題、プレゼン、レポート２つ、ディベートととにかくやることが多い', 'やることが多い。授業時間の前半に講義、後半にプレゼンやディベートの準備をする。毎週映像授業を見て月曜の9時までに感想と質問をMoodleに提出する。レポート課題のテーマが大雑把なのと書き方について言及がないため、よく分からないまま3000字のレポートを2回書くことになる。', '授業時間外に取り組まないといけないことが多いところ。', '課題が多く時間が取られてしまうところ'],
    otherInfo: ['先生は優しめで内容自体は結構個人的には面白い', '毎週どこかのグループが大学に関連するニュースを発表する。', '毎週の課題?授業動画の感想と内容に関する質問、教室授業の感想をmoodle上で提出する。 プレゼンテーション?今年（2025年度前期）は理想の大学入試制度に関するプレゼンをした。授業内で話し合いの時間は設けてくださるが、パワポに加えて配布資料も作ることになっていたので、相当要領良くやらない限り、授業以外の時間にもグループで集まる必要がある。 ディベート?今年は大学無償化の是非についてのディベートだった。プレゼン同様、授業内で話し合うことはできるが、根拠を集めて説得力のある論を賛否両方の立場で作らないといけないので、授業以外にグループで集まることになる可能性が高い。 大学ニュース?グループ持ち回りで（今年は3グループだったため3週に1回）、グループで大学に関するニュースを調べてこないといけない週がある。そのニュースに対する意見も聞かれるため、グループの全員が記事をちゃんと読んでおく必要がある。 中間・期末レポート?5月に中間レポート課題、7月に期末レポート課題が出された。提出期限は約1ヶ月後で、分量はそれぞれ2200字だった。専門家の意見を引用しているかどうかや、適切な形で引用されているかどうかなど、かなり細かく採点されるので、高得点が欲しかったら丁寧に作らないといけない。ただ、レポートのテーマは、プレゼンやディベートのために集めた情報を使えるものになっていたので、プレゼンやディベートの準備をちゃんとしていたら多少は書きやすくなると思う。 やることがかなり多く、大変な授業ではあるが、真面目にやればAAが取れると思うし力はつくと思う。楽して単位取りたい人は選ばないのが無難。', '2000字程度のレポートとグループワークが2回ずつある']
  },
];
